mysite/account/urls.py
# urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns=[
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('register/', views.register, name='register'),
]
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import RegisterView

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
     path('logout/', auth_views.LogoutView.as_view(next_page='account:login'), name='logout')
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pybo/", include('pybo.urls')),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path("data/", include('data.urls')),
]

mysite/data/urls.py
from django.urls import path
from . import views

app_name = 'data'

urlpatterns = [
    path('arrest/', views.arrest, name='arrest'),
    path('location/', views.location, name='location'),
    path('safemap/', views.safemap, name='safemap'),
    path('region/', views.region, name='region'),
    
]

mysite/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),

]

mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
]

mysite/account/models.py
from django.db import models

# Create your models here.

mysite/data/models.py
from django.db import models

# Create your models here.

class Region(models.Model):
    region = models.CharField(max_length=200)
    lat = models.TextField()
    loc = models.TextField()

    def __str__(self):
        return self.region
    
# from django.db import models

# # Create your models here.
# class Category(models.Model):  # 카테고리 모델 생성
#     # unique=True 코드를 넣으면 동일한 name을 갖는 카테고리를 만들 수 없다(길이 제한이 있는 문자열)
#     category_name = models.CharField(max_length=50, unique=True)
#     slug = models.SlugField(max_length=200, allow_unicode=True)

#     def __str__(self):
#         return self.category_name  # 카테고리 이름 리턴

#     def get_absolute_url(self):
#         # 카테코리 관리 페이지에서 view on site 버튼 생성 후 버튼 누르면 해당 카테고리 페이지로 이동
#         return f'/product/category/{self.slug}/'

#     class Meta:
#         verbose_name_plural = '카테고리'  # 관리자 페이지에서 카테고리 목록 이름을 categorys에서 categories로 변경
        
# class Product(models.Model) :
#     name = models.CharField(max_length=50, blank=True) # 이건 뭐여 있던디
#     category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)
#     manu_f =  models.CharField(max_length=50, blank=True)
#     company = models.CharField(max_length=50, blank=True)
#     price_buy = models.CharField(max_length=50, blank=True)
#     price_borrow = models.CharField(max_length=50, blank=True)
#     url_go = models.URLField()

#     def __str__(self) :
#         return f'[{self.pk}]{self.name}'

mysite/home/models.py
from django.db import models

# Create your models here.

mysite/pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject
    
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

mysite/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

mysite/account/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib import messages
from django.views import View

class CustomLoginView(LoginView):
    template_name = 'account/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('/')  # 로그인 성공 후 이동할 URL

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if form.errors:
            messages.error(self.request, "아이디 또는 비밀번호가 잘못되었습니다. 다시 시도해주세요.")
        return response
    
class RegisterView(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, 'account/register.html', {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '회원가입이 완료되었습니다. 로그인해주세요!')
            return redirect('account:login')  # 회원가입 후 로그인 페이지로 이동
        else:
            messages.error(request, '입력한 정보가 올바르지 않습니다. 다시 시도해주세요.')
        return render(request, 'account/register.html', {'form': form})
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')  # 회원가입 후 홈페이지로 이동
    else:
        form = CustomUserCreationForm()
    return render(request, 'account/register.html', {'form': form})

class RestrictedLoginView(CustomLoginView):
    pass

mysite/data/views.py
from django.shortcuts import render
from django.views import View
from collections import OrderedDict
from .fusioncharts import FusionCharts

# Create your views here.
def arrest(request) :
    return render(request, 'data/arrest.html')
def location(request) :
    return render(request, 'data/location.html')
def safemap(request) :
    return render(request, 'data/safemap.html')
def region(request) :
    return render(request, 'data/region.html')
    return render(request, 'data/region.html')

mysite/home/views.py
from django.shortcuts import render


def main(request) :
    return render(request, 'home/home.html')

mysite/pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.

from .models import Question
from django.utils import timezone

def index(request):
    """
    pybo 목록 출력
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)
    
def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question= get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question= get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'),
                              create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id)
    

mysite/data/templates/data/arrest.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Dashboard - SB Admin</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
 
        {% include 'home/navbar.html' %}
        <script type="text/javascript" src="{% static 'js/fusioncharts.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/fusioncharts.charts.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/themes/fusioncharts.theme.fusion.js' %}"></script>
        <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
        <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
        {% include 'home/navbar.html' %}

        <script type="text/javascript">
            FusionCharts.ready(function () {
                var chartConfig = {
                    type: 'column2d',
                    renderAt: 'chart-1',
                    width: '700',
                    height: '700',
                    dataSource: {
                        // 여기에 차트 데이터 및 설정 추가
                        "chart": {
                            "caption": "서울시 범죄 발생 수",
                            "xAxisName": "자치구",
                            "yAxisName": "발생",
                            "theme": "fusion"
                        },
                        "data": [{
                            "label": "중구",
                            "value": "42"
                        }, {
                            "label": "관악구",
                            "value": "81"
                        }, {
                            "label": "용산구",
                            "value": "72"
                        }]
                    }
                };
                var chart = new FusionCharts(chartConfig);
                chart.render();     //이거 반복문 돌려서 추가하면 될듯
                var newData = {
                    "label": "Apr",
                    "value": "61"
                    
                };
                // 차트 데이터 소스에 추가
                chartConfig.dataSource.data.push(newData);
                // 차트 새로고침
                chart.setChartData(chartConfig.dataSource);
                
                var chartConfig2 = {
                    type: 'column2d',
                    renderAt: 'chart-2',  // 두 번째 차트가 표시될 div의 ID
                    width: '700',
                    height: '700',
                    dataSource: {
                        // 두 번째 차트의 데이터 및 설정 추가
                        // 예시 데이터
                        "chart": {
                            "caption": "서울시 범죄 검거 수",
                            "xAxisName": "자치구",
                            "yAxisName": "검거",
                            "theme": "fusion"
                        },
                        "data": [{
                            "label": "Apr",
                            "value": "530000"
                        }, {
                            "label": "May",
                            "value": "670000"
                        }, {
                            "label": "Jun",
                            "value": "720000"
                        }]
                    }
                };
                var chart2 = new FusionCharts(chartConfig2);
                chart2.render();

            });
        </script>

    </head>
    <body class="sb-nav-fixed">
        <section id="hero" class="d-flex align-items-center">
            <div id="layoutSidenav">
              <div id="layoutSidenav_content">
                <main>
                  <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
                    <div class="row justify-content-center">
                      <div class="col-xl-7 col-lg-9 text-center">
                        <h1>Welcome to Crime Insight</h1>
                          <h2>범죄 정보 시각화 웹사이트입니다.</h2>
                      </div>
                    </div>
                    
                    <div class="row icon-boxes">
                      <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-box">
                          <div class="icon"><i class="ri-stack-line"></i></div>
                          <h4 class="title"><a href="{% url 'data:safemap' %}">Safe Map</a></h4>
                          <p class="description">안심귀가를 위해 안심 CCTV의 위치를 표시해주는 지도입니다.</p>
                        </div>
                      </div>
                   
                      <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
                        <div class="icon-box">
                          <div class="icon"><i class="ri-palette-line"></i></div>
                          <h4 class="title"><a href="{% url 'data:region' %}">지역별 범죄 정보</a></h4>
                          <p class="description">지역별로 범죄 유형 및 발생 건수에 대해 살펴봅니다.</p>
                        </div>
                        </div>
              
                      <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
                        <div class="icon-box">
                          <div class="icon"><i class="ri-command-line"></i></div>
                          <h4 class="title"><a href="{% url 'data:location' %}">장소별 범죄 정보</a></h4>
                          <p class="description">장소별로 범죄 유형 및 발생 건수에 대해 살펴봅니다.</p>
                        </div>
                      </div>
              
                      <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
                        <div class="icon-box">
                          <div class="icon"><i class="ri-fingerprint-line"></i></div>
                          <h4 class="title"><a href="{% url 'data:arrest' %}">검거율 정보</a></h4>
                          <p class="description">각 범죄 유형에 대한 검거율을 살펴봅니다.</p>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-area me-1"></i>
                                    Area Chart Example
                                </div>
                                <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                        <div class="col-xl-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <i class="fas fa-chart-bar me-1"></i>
                                    Bar Chart Example
                                </div>
                                <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                            </div>
                        </div>
                    </div>
                  </div>
                    <div class="d-flex justify-content-between align-items-center mt-4">
                        <div class="chart-container" style="width: 600; border-right: 1px solid black;">
                            <h3>범죄자 발생</h3>
                            <div id="chart-1">{{ output|safe }}</div>
                        </div>
                        <div class="chart-container" style="width: 600;">
                            <h3>범죄자 검거</h3>
                            <div id="chart-2"></div>
                        </div>
                    </div>
                </main>
              </div>
            </div>            
          </section>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2023</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
        <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
        <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
    </body>
</html>
</html>

mysite/data/templates/data/chart.html
{% load static %} 

<head>
    
    <script type="text/javascript" src="{% static "js/fusioncharts.js" %}"></script>
    <script type="text/javascript" src="{% static "js/fusioncharts.charts.js" %}"></script>
    <script type="text/javascript" src="{% static "js/themes/fusioncharts.theme.fusion.js" %}"></script>
	
    
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
</head>
<body>
  <div style="font-family: 'Helvetica Neue', Arial; font-size: 16px">
      <h3>{{ chartTitle|safe }}</h3>
      <div id="chart-1">{{ output|safe }}</div>
      <br/>
  </div>
</body>

mysite/home/templates/home/home.html
{% load static %} 
<!DOCTYPE html>
<html lang="en">
   <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Crime Insight</title>
        {% include 'home/navbar.html' %}
   </head> 
   <body class="sb-nav-fixed">
     <section id="hero" class="d-flex align-items-center">
       <div id="layoutSidenav" style="width=100%">
         <div id="layoutSidenav_content">
           <main>
             <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
               <div class="row justify-content-center">
                 <div class="col-xl-7 col-lg-9 text-center">
                   <h1>Welcome to Crime Insight</h1>
                     <h2>범죄 정보 시각화 웹사이트입니다.</h2>
                 </div>
               </div>
               
               <div class="row icon-boxes justify-content-center">
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-stack-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:safemap' %}">Safe Map</a></h4>
                     <p class="description">안심귀가를 위해 안심 CCTV의 위치를 표시해주는 지도입니다.</p>
                   </div>
                 </div>
              
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="700">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-palette-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:region' %}">지역별 범죄 정보</a></h4>
                     <p class="description">지역별로 범죄 유형 및 발생 건수에 대해 살펴봅니다.</p>
                   </div>
                   </div>
         
                 <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
                   <div class="icon-box">
                     <div class="icon"><i class="ri-command-line"></i></div>
                     <h4 class="title"><a href="{% url 'data:arrest' %}">범죄 발생 및 검거 정보</a></h4>
                     <p class="description">장소별로 범죄 유형 및 발생 건수에 대해 살펴봅니다.</p>
                   </div>
                 </div>
             </div>
           </main>
         </div>
       </div>            
     </section>
     <footer class="py-4 bg-light mt-auto">
         <div class="container-fluid px-4">
             <div class="d-flex align-items-center justify-content-between small">
                 <div class="text-muted">Copyright &copy; Your Website 2023</div>
                 <div>
                     <a href="#">Privacy Policy</a>
                     &middot;
                     <a href="#">Terms &amp; Conditions</a>
                 </div>
             </div>
         </div>
     </footer>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'js/scripts.js' %}"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
     <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
     <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
     <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
     <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
     <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
     <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
     <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
     <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
     <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
     <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
     <script src="{% static 'assets/js/main.js' %}"></script>
 </body>
</html>

mysite/home/templates/home/navbar.html
{% load static %} 
<link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark ">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="/">Crime Insight</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <!-- 사용자가 로그인되어 있을 때 -->
                        <p>안녕하세요, {{ user.username }}님!</p>
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">로그아웃</a></li>
                    {% else %}
                        <!-- 사용자가 로그인되어 있지 않을 때 -->
                        <li><a class="dropdown-item" href="{% url 'account:login' %}">로그인</a></li>
                    {% endif %}
                    
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" href="index.html">
                        <a class="nav-link" href="{% url 'data:safemap' %}">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Safe Map
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            범죄 통계
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">지역별 통계</a>
                                <a class="nav-link" href="layout-sidenav-light.html">장소별 통계</a>
                                <a class="nav-link" href="layout-sidenav-light.html">검거율 통계</a>
                                <a class="nav-link" href="{% url 'data:region' %}">지역별 통계</a>
                                <a class="nav-link" href="{% url 'data:location' %}">장소별 통계</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                        소통 게시판
                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">위험 구역 제보</a>
                                <a class="nav-link" href="layout-sidenav-light.html">CCTV 설치 신청</a>
                                <a class="nav-link" href="layout-sidenav-light.html">자유 게시판</a>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">참고 자료</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            범죄 관련 데이터 수집
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            최근 범죄 뉴스
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Love Lee:</div>
                    Crime Insight
                </div>
            </nav>
        </div>
    </div>
</body>

mysite/templates/pybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{question.subject}}</h1>
<div> 
    {{ question.content }} 
</div>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다. </h5>
<div>
    <ul>

        {% for answer in question.answer_set.all %}
            <li>{{ answer.content}}</li>
        {% endfor %}
    </ul>
</div>

<form action="{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name ="content" id="content" rows="15"></textarea>
<input type="submit" value="답변 등록">
</form>

mysite/templates/pybo/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
            {% if question_list %}
            {%for question in question_list%}
            <tr>
                <td>{{ forloop.counter}}</td>
                <td>
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{question.subject}}
                    </a>
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
            {%endfor%}
            {%else%}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>

{% comment %} {% if question_list %}
    <ul>
        {%for question in question_list %}
            <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %} {% endcomment %}